"""Deduplica el banco original: reemplaza las 3,000 variantes repetidas por los
33 conceptos únicos, con acentos corregidos y traducción al inglés."""
import json

# 33 conceptos únicos del banco original (acentuados + traducidos)
CONCEPTS = [
{"categoria":"Historia","subtema":"Independencia","dificultad":"media",
 "pregunta":"¿En qué año inició la Independencia de México?",
 "opciones":["1857","1821","1910","1810"],"respuesta":"1810",
 "explicacion":"La Independencia inició en 1810 con el Grito de Dolores.",
 "pregunta_en":"In what year did Mexico's Independence begin?",
 "opciones_en":["1857","1821","1910","1810"],
 "explicacion_en":"Independence began in 1810 with the Cry of Dolores."},
{"categoria":"Historia","subtema":"Independencia","dificultad":"media",
 "pregunta":"¿En qué año se consumó la Independencia de México?",
 "opciones":["1821","1857","1810","1917"],"respuesta":"1821",
 "explicacion":"La Independencia se consumó en 1821.",
 "pregunta_en":"In what year was Mexico's Independence achieved?",
 "opciones_en":["1821","1857","1810","1917"],
 "explicacion_en":"Independence was achieved in 1821."},
{"categoria":"Historia","subtema":"Independencia","dificultad":"media",
 "pregunta":"¿Qué personaje está asociado al Grito de Dolores?",
 "opciones":["Benito Juárez","Ignacio Zaragoza","Francisco I. Madero","Miguel Hidalgo y Costilla"],"respuesta":"Miguel Hidalgo y Costilla",
 "explicacion":"Miguel Hidalgo y Costilla encabezó el Grito de Dolores en 1810.",
 "pregunta_en":"Which figure is associated with the Cry of Dolores?",
 "opciones_en":["Benito Juárez","Ignacio Zaragoza","Francisco I. Madero","Miguel Hidalgo y Costilla"],
 "explicacion_en":"Miguel Hidalgo y Costilla led the Cry of Dolores in 1810."},
{"categoria":"Historia","subtema":"Independencia","dificultad":"facil",
 "pregunta":"¿En qué fecha se conmemora la Independencia de México?",
 "opciones":["20 de noviembre","16 de septiembre","5 de mayo","24 de febrero"],"respuesta":"16 de septiembre",
 "explicacion":"La Independencia se conmemora el 16 de septiembre.",
 "pregunta_en":"On what date is Mexico's Independence commemorated?",
 "opciones_en":["November 20","September 16","May 5","February 24"],
 "explicacion_en":"Independence is commemorated on September 16."},
{"categoria":"Historia","subtema":"Reforma","dificultad":"media",
 "pregunta":"¿A quién se le conoce como el Benemérito de las Américas?",
 "opciones":["Benito Juárez","Porfirio Díaz","Venustiano Carranza","Lázaro Cárdenas"],"respuesta":"Benito Juárez",
 "explicacion":"Benito Juárez es el Benemérito de las Américas.",
 "pregunta_en":"Who is known as the Benemérito de las Américas?",
 "opciones_en":["Benito Juárez","Porfirio Díaz","Venustiano Carranza","Lázaro Cárdenas"],
 "explicacion_en":"Benito Juárez is the Benemérito de las Américas."},
{"categoria":"Historia","subtema":"Reforma","dificultad":"media",
 "pregunta":"¿Qué leyes separaron a la Iglesia del Estado en México?",
 "opciones":["Constitución de Cádiz","Plan de Ayala","Leyes de Reforma","Plan de San Luis"],"respuesta":"Leyes de Reforma",
 "explicacion":"Las Leyes de Reforma separaron a la Iglesia del Estado.",
 "pregunta_en":"Which laws separated Church and State in Mexico?",
 "opciones_en":["Constitution of Cádiz","Plan of Ayala","Reform Laws","Plan of San Luis"],
 "explicacion_en":"The Reform Laws separated Church and State."},
{"categoria":"Historia","subtema":"Revolucion","dificultad":"media",
 "pregunta":"¿En qué año inició la Revolución Mexicana?",
 "opciones":["1921","1910","1900","1917"],"respuesta":"1910",
 "explicacion":"La Revolución Mexicana inició el 20 de noviembre de 1910.",
 "pregunta_en":"In what year did the Mexican Revolution begin?",
 "opciones_en":["1921","1910","1900","1917"],
 "explicacion_en":"The Mexican Revolution began on November 20, 1910."},
{"categoria":"Historia","subtema":"Revolucion","dificultad":"media",
 "pregunta":"¿Quién fue el autor del Plan de San Luis?",
 "opciones":["Francisco I. Madero","Emiliano Zapata","Victoriano Huerta","Plutarco Elías Calles"],"respuesta":"Francisco I. Madero",
 "explicacion":"Francisco I. Madero redactó el Plan de San Luis (1910).",
 "pregunta_en":"Who authored the Plan of San Luis?",
 "opciones_en":["Francisco I. Madero","Emiliano Zapata","Victoriano Huerta","Plutarco Elías Calles"],
 "explicacion_en":"Francisco I. Madero wrote the Plan of San Luis (1910)."},
{"categoria":"Historia","subtema":"Revolucion","dificultad":"media",
 "pregunta":"¿Qué lema está asociado a Emiliano Zapata?",
 "opciones":["Libertad de comercio","Tierra y Libertad","Orden y progreso","Sufragio efectivo, no reelección"],"respuesta":"Tierra y Libertad",
 "explicacion":"El lema de Emiliano Zapata fue «Tierra y Libertad».",
 "pregunta_en":"Which motto is associated with Emiliano Zapata?",
 "opciones_en":["Free trade","Land and Freedom","Order and progress","Effective suffrage, no reelection"],
 "explicacion_en":"Emiliano Zapata's motto was 'Land and Freedom'."},
{"categoria":"Historia","subtema":"Prehispanica","dificultad":"media",
 "pregunta":"¿Cuál fue la capital del imperio mexica?",
 "opciones":["Monte Albán","Palenque","Tenochtitlan","Teotihuacán"],"respuesta":"Tenochtitlan",
 "explicacion":"Tenochtitlan fue la capital del imperio mexica (azteca).",
 "pregunta_en":"What was the capital of the Mexica empire?",
 "opciones_en":["Monte Albán","Palenque","Tenochtitlan","Teotihuacán"],
 "explicacion_en":"Tenochtitlan was the capital of the Mexica (Aztec) empire."},
{"categoria":"Historia","subtema":"Prehispanica","dificultad":"media",
 "pregunta":"¿Qué civilización está asociada a Chichén Itzá?",
 "opciones":["Olmeca","Maya","Purépecha","Mexica"],"respuesta":"Maya",
 "explicacion":"Chichén Itzá fue una gran ciudad de la civilización maya.",
 "pregunta_en":"Which civilization is associated with Chichén Itzá?",
 "opciones_en":["Olmec","Maya","Purépecha","Mexica"],
 "explicacion_en":"Chichén Itzá was a great city of the Maya civilization."},
{"categoria":"Civica","subtema":"Constitucion","dificultad":"facil",
 "pregunta":"¿Cuál es la Constitución vigente de México?",
 "opciones":["Constitución de Cádiz","Constitución de 1824","Constitución Política de los Estados Unidos Mexicanos de 1917","Constitución de 1857"],"respuesta":"Constitución Política de los Estados Unidos Mexicanos de 1917",
 "explicacion":"La Constitución vigente es la de 1917.",
 "pregunta_en":"What is Mexico's current Constitution?",
 "opciones_en":["Constitution of Cádiz","Constitution of 1824","Political Constitution of the United Mexican States of 1917","Constitution of 1857"],
 "explicacion_en":"The current Constitution is that of 1917."},
{"categoria":"Civica","subtema":"Constitucion","dificultad":"facil",
 "pregunta":"¿Cuántos poderes tiene la Unión (división de poderes)?",
 "opciones":["4","5","2","3"],"respuesta":"3",
 "explicacion":"Los tres poderes son Ejecutivo, Legislativo y Judicial.",
 "pregunta_en":"How many branches of government does the Union have?",
 "opciones_en":["4","5","2","3"],
 "explicacion_en":"The three branches are Executive, Legislative and Judicial."},
{"categoria":"Civica","subtema":"Instituciones","dificultad":"facil",
 "pregunta":"¿Qué poder elabora y reforma las leyes en México?",
 "opciones":["Poder Ejecutivo","Poder Electoral","Poder Judicial","Poder Legislativo"],"respuesta":"Poder Legislativo",
 "explicacion":"El Poder Legislativo elabora y reforma las leyes.",
 "pregunta_en":"Which branch makes and reforms laws in Mexico?",
 "opciones_en":["Executive","Electoral","Judicial","Legislative"],
 "explicacion_en":"The Legislative branch makes and reforms laws."},
{"categoria":"Civica","subtema":"Instituciones","dificultad":"facil",
 "pregunta":"¿Qué poder administra el gobierno federal en México?",
 "opciones":["Poder Legislativo","Poder Ejecutivo","Poder Judicial","Poder Municipal"],"respuesta":"Poder Ejecutivo",
 "explicacion":"El Poder Ejecutivo administra el gobierno federal.",
 "pregunta_en":"Which branch administers the federal government in Mexico?",
 "opciones_en":["Legislative","Executive","Judicial","Municipal"],
 "explicacion_en":"The Executive branch administers the federal government."},
{"categoria":"Civica","subtema":"Instituciones","dificultad":"facil",
 "pregunta":"¿Qué poder resuelve las controversias jurídicas en México?",
 "opciones":["Poder Legislativo","Poder Judicial","Poder Electoral","Poder Ejecutivo"],"respuesta":"Poder Judicial",
 "explicacion":"El Poder Judicial resuelve controversias jurídicas.",
 "pregunta_en":"Which branch resolves legal disputes in Mexico?",
 "opciones_en":["Legislative","Judicial","Electoral","Executive"],
 "explicacion_en":"The Judicial branch resolves legal disputes."},
{"categoria":"Civica","subtema":"Instituciones","dificultad":"facil",
 "pregunta":"¿Cuánto dura el mandato presidencial en México?",
 "opciones":["6 años","5 años","4 años","3 años"],"respuesta":"6 años",
 "explicacion":"El mandato presidencial dura 6 años (sexenio), sin reelección.",
 "pregunta_en":"How long does the presidential term last in Mexico?",
 "opciones_en":["6 years","5 years","4 years","3 years"],
 "explicacion_en":"The presidential term lasts 6 years, without reelection."},
{"categoria":"Civica","subtema":"Instituciones","dificultad":"facil",
 "pregunta":"¿Qué institución organiza las elecciones federales en México?",
 "opciones":["Secretaría de Gobernación","Instituto Nacional Electoral (INE)","CNDH","Fiscalía General de la República"],"respuesta":"Instituto Nacional Electoral (INE)",
 "explicacion":"El INE organiza las elecciones federales.",
 "pregunta_en":"Which institution organizes federal elections in Mexico?",
 "opciones_en":["Ministry of the Interior","National Electoral Institute (INE)","CNDH","Attorney General's Office"],
 "explicacion_en":"The INE organizes federal elections."},
{"categoria":"Geografia","subtema":"Nacional","dificultad":"facil",
 "pregunta":"¿Cuál es la capital de México?",
 "opciones":["Monterrey","Puebla","Ciudad de México","Guadalajara"],"respuesta":"Ciudad de México",
 "explicacion":"La capital del país es la Ciudad de México.",
 "pregunta_en":"What is Mexico's capital?",
 "opciones_en":["Monterrey","Puebla","Mexico City","Guadalajara"],
 "explicacion_en":"The country's capital is Mexico City."},
{"categoria":"Geografia","subtema":"Nacional","dificultad":"facil",
 "pregunta":"¿Cuántas entidades federativas tiene México?",
 "opciones":["32","31","33","30"],"respuesta":"32",
 "explicacion":"México tiene 31 estados y la Ciudad de México (32 entidades).",
 "pregunta_en":"How many federative entities does Mexico have?",
 "opciones_en":["32","31","33","30"],
 "explicacion_en":"Mexico has 31 states plus Mexico City (32 entities)."},
{"categoria":"Geografia","subtema":"Nacional","dificultad":"facil",
 "pregunta":"¿Qué océano se encuentra al oeste de México?",
 "opciones":["Océano Índico","Océano Ártico","Océano Atlántico","Océano Pacífico"],"respuesta":"Océano Pacífico",
 "explicacion":"Al oeste de México está el océano Pacífico.",
 "pregunta_en":"Which ocean lies to the west of Mexico?",
 "opciones_en":["Indian Ocean","Arctic Ocean","Atlantic Ocean","Pacific Ocean"],
 "explicacion_en":"The Pacific Ocean lies to the west of Mexico."},
{"categoria":"Geografia","subtema":"Nacional","dificultad":"media",
 "pregunta":"¿Qué países limitan con México al sureste?",
 "opciones":["Guatemala y Belice","Honduras y El Salvador","Panamá y Colombia","Nicaragua y Costa Rica"],"respuesta":"Guatemala y Belice",
 "explicacion":"México limita al sureste con Guatemala y Belice.",
 "pregunta_en":"Which countries border Mexico to the southeast?",
 "opciones_en":["Guatemala and Belize","Honduras and El Salvador","Panama and Colombia","Nicaragua and Costa Rica"],
 "explicacion_en":"Mexico borders Guatemala and Belize to the southeast."},
{"categoria":"Geografia","subtema":"Nacional","dificultad":"facil",
 "pregunta":"¿Qué golfo se ubica al este de México?",
 "opciones":["Golfo de México","Golfo de Tehuantepec","Golfo de California","Golfo de Alaska"],"respuesta":"Golfo de México",
 "explicacion":"Al este de México se encuentra el Golfo de México.",
 "pregunta_en":"Which gulf lies to the east of Mexico?",
 "opciones_en":["Gulf of Mexico","Gulf of Tehuantepec","Gulf of California","Gulf of Alaska"],
 "explicacion_en":"The Gulf of Mexico lies to the east of Mexico."},
{"categoria":"Geografia","subtema":"Nacional","dificultad":"facil",
 "pregunta":"¿Qué mar se encuentra al este de la península de Yucatán?",
 "opciones":["Mar Caribe","Mar Mediterráneo","Mar de Cortés","Mar Rojo"],"respuesta":"Mar Caribe",
 "explicacion":"Al este de la península de Yucatán está el mar Caribe.",
 "pregunta_en":"Which sea lies to the east of the Yucatán peninsula?",
 "opciones_en":["Caribbean Sea","Mediterranean Sea","Sea of Cortés","Red Sea"],
 "explicacion_en":"The Caribbean Sea lies to the east of the Yucatán peninsula."},
{"categoria":"Cultura","subtema":"Simbolos","dificultad":"facil",
 "pregunta":"¿Cuáles son los colores de la bandera nacional de México?",
 "opciones":["Verde, blanco y rojo","Blanco, negro y rojo","Rojo, azul y blanco","Verde, rojo y azul"],"respuesta":"Verde, blanco y rojo",
 "explicacion":"La bandera mexicana es verde, blanca y roja.",
 "pregunta_en":"What are the colors of Mexico's national flag?",
 "opciones_en":["Green, white and red","White, black and red","Red, blue and white","Green, red and blue"],
 "explicacion_en":"The Mexican flag is green, white and red."},
{"categoria":"Cultura","subtema":"Simbolos","dificultad":"facil",
 "pregunta":"¿Qué animal aparece en el escudo nacional de México?",
 "opciones":["Águila","Jaguar","Cóndor","Venado"],"respuesta":"Águila",
 "explicacion":"El escudo nacional muestra un águila real sobre un nopal.",
 "pregunta_en":"Which animal appears on Mexico's coat of arms?",
 "opciones_en":["Eagle","Jaguar","Condor","Deer"],
 "explicacion_en":"The coat of arms shows a golden eagle on a cactus."},
{"categoria":"Cultura","subtema":"Simbolos","dificultad":"facil",
 "pregunta":"¿En qué fecha se celebra el Día de la Bandera en México?",
 "opciones":["24 de febrero","5 de febrero","20 de noviembre","16 de septiembre"],"respuesta":"24 de febrero",
 "explicacion":"El Día de la Bandera se celebra el 24 de febrero.",
 "pregunta_en":"On what date is Flag Day celebrated in Mexico?",
 "opciones_en":["February 24","February 5","November 20","September 16"],
 "explicacion_en":"Flag Day is celebrated on February 24."},
{"categoria":"Cultura","subtema":"Patrimonio","dificultad":"facil",
 "pregunta":"¿Qué celebración mexicana está reconocida por la UNESCO como patrimonio inmaterial de la humanidad?",
 "opciones":["Nochebuena","Semana Santa","Carnaval de Veracruz","Día de Muertos"],"respuesta":"Día de Muertos",
 "explicacion":"El Día de Muertos es Patrimonio Cultural Inmaterial de la Humanidad.",
 "pregunta_en":"Which Mexican celebration is recognized by UNESCO as intangible heritage of humanity?",
 "opciones_en":["Christmas Eve","Holy Week","Veracruz Carnival","Day of the Dead"],
 "explicacion_en":"The Day of the Dead is Intangible Cultural Heritage of Humanity."},
{"categoria":"Cultura","subtema":"Patrimonio","dificultad":"facil",
 "pregunta":"¿Cuál es el alimento base de la cocina tradicional mexicana?",
 "opciones":["Avena","Maíz","Centeno","Cebada"],"respuesta":"Maíz",
 "explicacion":"El maíz es la base de la cocina tradicional mexicana.",
 "pregunta_en":"What is the staple food of traditional Mexican cuisine?",
 "opciones_en":["Oats","Maize","Rye","Barley"],
 "explicacion_en":"Maize is the base of traditional Mexican cuisine."},
{"categoria":"Cultura","subtema":"Patrimonio","dificultad":"facil",
 "pregunta":"¿Qué platillo tradicional mexicano se envuelve en hoja?",
 "opciones":["Tamales","Chilaquiles","Pozole","Enchiladas"],"respuesta":"Tamales",
 "explicacion":"Los tamales se envuelven en hojas de maíz o de plátano.",
 "pregunta_en":"Which traditional Mexican dish is wrapped in leaves?",
 "opciones_en":["Tamales","Chilaquiles","Pozole","Enchiladas"],
 "explicacion_en":"Tamales are wrapped in corn or banana leaves."},
{"categoria":"Cultura","subtema":"Patrimonio","dificultad":"media",
 "pregunta":"¿Cuál es la lengua indígena más hablada en México?",
 "opciones":["Quechua","Aimara","Náhuatl","Guaraní"],"respuesta":"Náhuatl",
 "explicacion":"El náhuatl es la lengua indígena con más hablantes en México.",
 "pregunta_en":"Which is the most widely spoken indigenous language in Mexico?",
 "opciones_en":["Quechua","Aymara","Nahuatl","Guaraní"],
 "explicacion_en":"Nahuatl is the indigenous language with the most speakers in Mexico."},
{"categoria":"Cultura","subtema":"Arte","dificultad":"media",
 "pregunta":"¿Qué muralista mexicano es reconocido internacionalmente?",
 "opciones":["Juan Rulfo","Octavio Paz","Diego Rivera","Carlos Fuentes"],"respuesta":"Diego Rivera",
 "explicacion":"Diego Rivera es el muralista mexicano más reconocido.",
 "pregunta_en":"Which Mexican muralist is internationally recognized?",
 "opciones_en":["Juan Rulfo","Octavio Paz","Diego Rivera","Carlos Fuentes"],
 "explicacion_en":"Diego Rivera is the most recognized Mexican muralist."},
{"categoria":"Cultura","subtema":"Arte","dificultad":"media",
 "pregunta":"¿Qué artista mexicana es famosa por sus autorretratos?",
 "opciones":["Nahui Olin","María Izquierdo","Frida Kahlo","Rosario Castellanos"],"respuesta":"Frida Kahlo",
 "explicacion":"Frida Kahlo es célebre por sus autorretratos.",
 "pregunta_en":"Which Mexican artist is famous for her self-portraits?",
 "opciones_en":["Nahui Olin","María Izquierdo","Frida Kahlo","Rosario Castellanos"],
 "explicacion_en":"Frida Kahlo is famous for her self-portraits."},
]

def main():
    bank = json.load(open("data/questions.json", encoding="utf-8"))
    # conserva las preguntas redactadas desde las imágenes
    authored = [q for q in bank if (q.get("fuente") or "").startswith("Imágenes")]
    next_id = 1
    out = []
    for c in CONCEPTS:
        assert c["respuesta"] in c["opciones"], c["pregunta"]
        out.append({
            "id": next_id, "seccion": "historia_cultura",
            "categoria": c["categoria"], "subtema": c["subtema"],
            "dificultad": c["dificultad"], "pregunta": c["pregunta"],
            "respuesta": c["respuesta"], "opciones": c["opciones"],
            "explicacion": c["explicacion"],
            "fuente": "Banco original (deduplicado) — SRE Guía de estudios de naturalización",
            "pregunta_en": c["pregunta_en"], "opciones_en": c["opciones_en"],
            "explicacion_en": c["explicacion_en"],
        })
        next_id += 1
    for q in authored:
        q = dict(q); q["id"] = next_id; next_id += 1
        out.append(q)
    json.dump(out, open("data/questions.json", "w", encoding="utf-8"), ensure_ascii=False, indent=2)
    print(f"Deduped original -> {len(CONCEPTS)} concepts + {len(authored)} authored = {len(out)} total.")

if __name__ == "__main__":
    main()
